# Generated by Django 4.2.14 on 2024-12-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
