# Generated by Django 4.2.14 on 2024-12-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctors_address_doctors_email_doctors_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
